// src/lib/components/emopic/BgCanvas.svelte
<script lang="ts">
    import {onMount} from 'svelte';
    import {BgCanvas} from '../../utils/BgCanvas';

    let ref: HTMLCanvasElement;

    onMount(() => {
      const canvas = ref ? new BgCanvas(ref) : undefined;
      const handleClick = () => (canvas?.draw());
      window.addEventListener('click', handleClick);

      return () => {
        canvas?.stop();
        window.removeEventListener('click', handleClick);
      }
    })
</script>

<canvas bind:this={ref} class="absolute inset-0 w-full h-full"></canvas>

// src/components/content/bg-canvas/bg-canvas.tsx
import {component$, Host, useClientEffect$, useRef, useStore} from '@builder.io/qwik';
import {Canvas} from '../../../utils/bg-canvas';

export const BgCanvas = component$(
  () => {
    const ref = useRef<HTMLCanvasElement>();
    useClientEffect$(() => {
      const canvas = ref.current ? new Canvas(ref.current) : undefined;

      canvas?.start();
      return () => {
        canvas?.stop();
      }
    });
    return (<Host class="absolute inset-0 w-full h-full" ref={ref}/>)
  },
  {
    tagName: 'canvas',
  }
);
